import { CircleGauge, Inbox, LockKeyhole, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ProductivityChart } from "@/components/productivity-chart";
import { StatusBadge } from "@/components/status-badge";
import { getDashboardData } from "@/lib/data/dashboard";

export const metadata = { title: "Produtividade" };

export default async function DashboardPage() {
  const dashboard = await getDashboardData(7);
  return <><PageHeader title="Produtividade da equipe" description="Dados consolidados do Supabase a partir da etapa Nova entrada no Bitrix24." action={<span className="button button-quiet">Ultimos {dashboard.periodo_dias} dias</span>}/><section className="kpi-strip"><div><span className="stat-symbol stat-info"><Inbox size={19}/></span><span><small>Disponiveis agora</small><strong>{dashboard.disponiveis}</strong><em className="trend neutral">na etapa Nova entrada</em></span></div><div><span className="stat-symbol stat-success"><CircleGauge size={19}/></span><span><small>Captadas no periodo</small><strong>{dashboard.captadas_periodo}</strong><em className="trend neutral">ultimos {dashboard.periodo_dias} dias</em></span></div><div><span className="stat-symbol stat-warning"><UsersRound size={19}/></span><span><small>Taxa de tratamento</small><strong>{dashboard.taxa_tratamento.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%</strong><em className="trend neutral">{dashboard.trabalhadas_periodo} trabalhadas</em></span></div><div><span className="stat-symbol stat-danger"><LockKeyhole size={19}/></span><span><small>Bloqueados agora</small><strong>{dashboard.bloqueados}</strong><em className="trend neutral">de {dashboard.corretores_ativos} corretores ativos</em></span></div></section><section className="dashboard-grid"><article className="chart-panel"><div className="section-heading"><div><h2>Ritmo da operacao</h2><p>Captadas versus trabalhadas no Bitrix24.</p></div><div className="chart-legend"><span><i className="legend-primary"/>Captadas</span><span><i className="legend-accent"/>Trabalhadas</span></div></div><ProductivityChart data={dashboard.serie}/></article><article className="ranking-panel"><div className="section-heading"><div><h2>Capacidade da equipe</h2><p>Uso do limite diario.</p></div></div>{dashboard.capacidade.length === 0 ? <p className="empty-copy">Nenhum corretor ativo cadastrado.</p> : dashboard.capacidade.map((broker) => <div className="capacity-row" key={broker.id}><span><strong>{broker.nome}</strong><small>{broker.capturados} de {broker.limite} captadas</small></span><div className="mini-progress"><i style={{ width: `${Math.min(100, broker.capturados / broker.limite * 100)}%` }}/></div>{broker.status === "bloqueado" ? <StatusBadge tone="danger">Bloqueado</StatusBadge> : broker.status === "auditoria" ? <StatusBadge tone="warning">Auditoria</StatusBadge> : <StatusBadge tone="success">Ativo</StatusBadge>}</div>)}</article></section></>;
}
